<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHO4xt7L\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHO4xt7L/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHO4xt7L.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHO4xt7L\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHO4xt7L\App_KernelDevDebugContainer([
    'container.build_hash' => 'HO4xt7L',
    'container.build_id' => '7808dc5f',
    'container.build_time' => 1771460948,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHO4xt7L');
