<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3NTZx1p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3NTZx1p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3NTZx1p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3NTZx1p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3NTZx1p\App_KernelDevDebugContainer([
    'container.build_hash' => '3NTZx1p',
    'container.build_id' => '2eaaefe6',
    'container.build_time' => 1774055991,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3NTZx1p');
