<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6SWZeHB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6SWZeHB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6SWZeHB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6SWZeHB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6SWZeHB\App_KernelDevDebugContainer([
    'container.build_hash' => '6SWZeHB',
    'container.build_id' => '89a4f0ba',
    'container.build_time' => 1747781063,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6SWZeHB');
