<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_telegram_items' => [[], ['_controller' => 'App\\Controller\\TelegramItemsController::index'], [], [['text', '/telegram/download']], [], [], []],
    'App\Controller\TelegramItemsController::index' => [[], ['_controller' => 'App\\Controller\\TelegramItemsController::index'], [], [['text', '/telegram/download']], [], [], []],
];
