<?php

namespace ContainerZyA4ziD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportTelegramCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ImportTelegram\ImportTelegramCommand' shared autowired service.
     *
     * @return \App\Command\ImportTelegram\ImportTelegramCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ImportTelegram/ImportTelegramCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CouchDB.php';
        include_once \dirname(__DIR__, 4).'/src/Service/MadelineTelegram.php';

        $container->privates['App\\Command\\ImportTelegram\\ImportTelegramCommand'] = $instance = new \App\Command\ImportTelegram\ImportTelegramCommand(($container->privates['App\\Service\\MadelineTelegram'] ??= new \App\Service\MadelineTelegram($container->getEnv('APP_ROOT_DIR'))), new \App\Service\CouchDB('telegram_messages_2'));

        $instance->setName('app:import-telegram');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
