<?php

namespace ContainerQj9zY2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTelegramItemsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TelegramItemsController' shared autowired service.
     *
     * @return \App\Controller\TelegramItemsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TelegramItemsController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/MadelineTelegram.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CouchDB.php';

        $container->services['App\\Controller\\TelegramItemsController'] = $instance = new \App\Controller\TelegramItemsController(($container->privates['App\\Service\\MadelineTelegram'] ??= new \App\Service\MadelineTelegram($container->getEnv('APP_ROOT_DIR'))), ($container->privates['App\\Service\\CouchDB'] ??= new \App\Service\CouchDB('telegram_messages_2')));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'router' => ['services', 'router', 'getRouterService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'router' => '?',
            'request_stack' => '?',
            'http_kernel' => '?',
            'serializer' => '?',
            'parameter_bag' => '?',
        ]))->withContext('App\\Controller\\TelegramItemsController', $container));

        return $instance;
    }
}
