<?php

namespace ContainerHO4xt7L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\TelegramItemsController::uploadItemToServer' => ['privates', '.service_locator.GL345QQ.App\\Controller\\TelegramItemsController::uploadItemToServer()', 'getTelegramItemsControlleruploadItemToServerService', true],
            'App\\Controller\\TelegramItemsController::downloadModelFromServer' => ['privates', '.service_locator.GL345QQ.App\\Controller\\TelegramItemsController::downloadModelFromServer()', 'getTelegramItemsControllerdownloadModelFromServerService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\TelegramItemsController:uploadItemToServer' => ['privates', '.service_locator.GL345QQ.App\\Controller\\TelegramItemsController::uploadItemToServer()', 'getTelegramItemsControlleruploadItemToServerService', true],
            'App\\Controller\\TelegramItemsController:downloadModelFromServer' => ['privates', '.service_locator.GL345QQ.App\\Controller\\TelegramItemsController::downloadModelFromServer()', 'getTelegramItemsControllerdownloadModelFromServerService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\TelegramItemsController::uploadItemToServer' => '?',
            'App\\Controller\\TelegramItemsController::downloadModelFromServer' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\TelegramItemsController:uploadItemToServer' => '?',
            'App\\Controller\\TelegramItemsController:downloadModelFromServer' => '?',
        ]));
    }
}
