<?php

namespace ContainerHO4xt7L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTelegramItemsControllerdownloadModelFromServerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GL345QQ.App\Controller\TelegramItemsController::downloadModelFromServer()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GL345QQ.App\\Controller\\TelegramItemsController::downloadModelFromServer()'] = ($container->privates['.service_locator.GL345QQ'] ?? $container->load('get_ServiceLocator_GL345QQService'))->withContext('App\\Controller\\TelegramItemsController::downloadModelFromServer()', $container);
    }
}
